package org.thewalk.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

@Entity @Table(name="PRODUCT_CATEGORY")
@Setter @Getter
public class ProductCategory {
	@Id  @Column(name="ID")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;
	
	@Column(name="CATEGORY_NAME")
	private String name;
	
	// default constructor is added by compiler to bytecode
	//setter n getter  generated by lombok
	
}
