use deandemo;
CREATE TABLE EMPLOYEE
(
	EMP_ID  INT PRIMARY KEY,
    EMP_NAME VARCHAR(30) NOT NULL,
    SALARY DOUBLE DEFAULT 0,
    DEPT_ID	int default 101
);
-- DML OPERATION
INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, SALARY) VALUES(1,'DEAN', 2300.00);
INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, SALARY) VALUES(2,'ALEX', 1203.10);
INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, SALARY, DEPT_ID) VALUES(3,'TOM', 3203.10,102);
-- DQL OPERATION
SELECT EMP_ID, EMP_NAME, SALARY, DEPT_ID FROM EMPLOYEE;
SELECT * FROM EMPLOYEE;
SELECT EMP_NAME, SALARY FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE EMP_ID=2;
SELECT * FROM EMPLOYEE WHERE SALARY > 2000;
UPDATE employee set SALARY=SALARY * 1.10 WHERE EMP_ID=1;
UPDATE employee set SALARY=SALARY * 1.10; 
DELETE FROM EMPLOYEE WHERE DEPT_ID=103;

-- DROP TABLE EMPLOYEE;
-- TRUNCATE TABLE EMPLOYEE;
ALTER TABLE EMPLOYEE RENAME COLUMN EMP_NAME TO NAME;
-- ALTER TABLE EMPLOYEE DROP COLUMN EMP_NAME;
-- ALTER TABLE EMPLOYEE ADD COLUMN ADDRESS VARCHAR(20);

CREATE TABLE DEPARTMENT(
	DEPT_ID INT,
    DEPT_NAME VARCHAR(20),
    LOCATION VARCHAR(20),
    CONSTRAINT pk_dept_id PRIMARY KEY(DEPT_ID)
);
-- ALTER TABLE DEPARTMENT DROP CONSTRAINT pk_dept_id

SELECT *  FROM DEPARTMENT;
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_DEPARTMENT_DEPT_ID foreign key(DEPT_ID) references DEPARTMENT(DEPT_ID) ; 

SELECT * FROM EMPLOYEE;
-- INNER JOIN
SELECT EMP_ID, NAME,  EMPLOYEE.DEPT_ID, DEPT_NAME ,LOCATION FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID=DEPARTMENT.DEPT_ID;
